### ISSUE TITLE
USD formatting incorrectly

### ISSUE THREAD

**Issue by hotmeteor** [akaunting/money#1]
Your documentation shows USD being formatted as:
```php
echo Money::USD(500); // '$ 5,00' unconverted
```
or `$5,00`

However, USD would actually be formatted as `$5.00`. Seems like a fairly fundamental error.

**Comment by ninjaparade** [comment]
Please advise once this error has been resolved.

**Comment by denisdulici** [comment]
That's just a readme typo.

**Comment by hotmeteor** [comment]
Super, thanks.
