### ISSUE TITLE
invalid currency "USD (US DOLLAR)"

### ISSUE THREAD

**Issue by BostonKenne** [akaunting/money#13]
Hi, 
I'm trying to use this featured inside my app, but i got this Error:
message

`Invalid currency "USD (US DOLLAR)"`

Thanks for help!

![image](https://user-images.githubusercontent.com/19219342/41870433-5b9eb004-78bc-11e8-9294-6e7ba79a99b5.png)

![image](https://user-images.githubusercontent.com/19219342/41870509-90a1f2b6-78bc-11e8-81cf-bd94b2869db2.png)

**Comment by denisdulici** [comment]
You're using it wrong Boston, try the following plz:

`$facture->prix = new Money(8000, new Currency('USD'), true);`

**Comment by Parables** [comment]
I disagree, I have tried everything but I am still getting this same error:

```php
$money = new Money( amount: 150, currency: new Currency('GHS'), convert: true);
```

```
{
  "Message": "Invalid currency \"GHS (GHANA CEDI)\"",
  "Exception": "OutOfBoundsException",
  "File": "C:\\xampp\\htdocs\\myapp\\vendor\\akaunting\\laravel-money\\src\\Currency.php",
  "Line": 222,
```

**Comment by Parables** [comment]
Turns out the issue was caused by using Macros. I need some additional methods on the Money class so I created some macros and registered them in a ServiceProvider's `boot()` method.

```php
Money::macro(
    'toString',
    fn (): string => $this->format()
);
```

I guess the only way to extend this is by creating a wrapper class for Money.
