### ISSUE TITLE
up to date ISO standards

### ISSUE THREAD

**Issue by dakira** [akaunting/money#2]
Hey, I don't want to criticize your work.. just an idea: There is an ISO standard and a publicly available library that has the current data on how prices should be formatted. It is already perfectly implemented with all bells ans whistles by [moneyphp/money](https://github.com/moneyphp/money). So to prevent yourself from having to update the formatting data all the time, don't you think it would be a better idea to make this package a Laravel wrapper for moneyphp?

**Comment by denisdulici** [comment]
Hello Matthias, np 😉  Because `moneytphp` uses the `intl` extension for number formatting. `intl` extension isn't present by default on PHP installs and can give [different results](http://moneyphp.org/en/latest/features/formatting.html#intl-formatter) in different environments.

```
https://github.com/moneyphp/money/blob/master/resources/currency.php
https://github.com/akaunting/money/blob/master/src/Config/money.php
```
