### ISSUE TITLE
new self() vs new static()

### ISSUE THREAD

**Issue by EricReichenbach** [akaunting/money#29]
I'm not sure if it's a bug or a feature but the calculation functions return a new instance of `self()`.

Returning a `new static()` would allow better inheritance behaviours (getting an new object of the current class instead of an instance of the base Money class).

**Comment by denisdulici** [comment]
Not really a feature. Would you mind to send a PR?

**Comment by EricReichenbach** [comment]
Cool, I've submitted a PR. 👍
