### ISSUE TITLE
Precision when multiplying with float?

### ISSUE THREAD

**Issue by moynzzz** [akaunting/money#30]
Hello I'm doing the following calculation:

```php
$amount = Money::EUR(9667);
$tax = $amount->multiply(20 / 100);
echo $tax->getAmount(); // This outputs "1933.4"?
```

The output is 1933.4 but shouldn't it be "1933"?

**Comment by denisdulici** [comment]
You can change the precision for that currency from the config file.

**Comment by jenky** [comment]
> You can change the precision for that currency from the config file.

No, this is not right since amount should be `int`. Precision should be applied to `value` not the `amount`. This making the `amount` type inconsistent and will be a big trouble when storing value to the DB column
