### ISSUE TITLE
How to convert float amount to int?

### ISSUE THREAD

**Issue by madsem** [akaunting/money#34]
Great package, thanks for the hard work.

I don't understand how to convert full currency amounts like `12.67` to int `1267`, or is that not part of the library?

**Comment by denisdulici** [comment]
Unfortunately, that's not part of the package.

**Comment by madsem** [comment]
@denisdulici thanks! But I solved it by doing 'money(...)->getAmount()' & 'money(...)->getValue()'. But now that you say this isn't supported, I'm wondering if that isn't correct?
