### ISSUE TITLE
Abandoned packages

### ISSUE THREAD

**Issue by netzhelden** [akaunting/money#36]
I am getting the following warnings during the installation:

```
Package operations: 1 install, 0 updates, 0 removals
  - Installing akaunting/money (1.0.14): Loading from cache
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.
```

**Comment by denisdulici** [comment]
Those are not related to this package https://github.com/akaunting/money/blob/master/composer.json

**Comment by netzhelden** [comment]
Sorry, my bad. There have been old Laravel/Passport dependencies and I just added your package and assumed it was there. My bad, I should have had a look for `composer.json` first. Thanks for your package, it works fine :-)

**Comment by denisdulici** [comment]
No problem, enjoy it ;-)
