### ISSUE TITLE
Error faced right after installation Laravel 7.0

### ISSUE THREAD

**Issue by Blair2004** [akaunting/money#37]
Hi, right after having used the CLI command to install on Laravel 7.0, there has been an error.

![screenshot-newtab-2020 05 08-12_15_53](https://user-images.githubusercontent.com/5265663/81400736-b681d180-9125-11ea-83ac-7c00150f4fcc.jpg)

I'll see later if that could be fixed quickly.

**Comment by carlomigueldy** [comment]
Try to delete manually the cached files from `/bootstrap/cache` and also delete `vendor`

Then reinstall all the packages via `composer install`
