### ISSUE TITLE
FatalThrowableError when attempting to install via composer require akaunting/money

### ISSUE THREAD

**Issue by mlars84** [akaunting/money#40]
https://github.com/akaunting/money/blob/75f6d0d036cd1ca82c2926cfae5a7c2759445cfb/src/Currency.php#L285

When attempting to install with `composer require akaunting/money` I am getting this exception: 
`Symfony\Component\Debug\Exception\FatalThrowableError  : Argument 1 passed to Akaunting\Money\Currency::setCurrencies() must be of the type array, null given, called in /Users/matthewlarson/Projects/ufr-workit-web-4.0/vendor/akaunting/money/src/Provider.php on line 22

  at /Users/matthewlarson/Projects/ufr-workit-web-4.0/vendor/akaunting/money/src/Currency.php:285
    281|      * @param array $currencies
    282|      *
    283|      * @return void
    284|      */
  > 285|     public static function setCurrencies(array $currencies)
    286|     {
    287|         static::$currencies = $currencies;
    288|     }
    289|

  Exception trace:

  1   Akaunting\Money\Currency::setCurrencies()
      /Users/matthewlarson/Projects/ufr-workit-web-4.0/vendor/akaunting/money/src/Provider.php:22

  2   Akaunting\Money\Provider::boot()
      /Users/matthewlarson/Projects/ufr-workit-web-4.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32`

I am using Laravel 6.2.

**Comment by Sameer911** [comment]
same issue to me using laravel 7

**Comment by denisdulici** [comment]
Not able to reproduce it on Akaunting which uses Laravel 7 https://github.com/akaunting/akaunting

**Comment by mlambley** [comment]
Just FYI I was able to replicate this, and I have a fix. The issue is when the config is already cached using `config:cache` before the `\Akaunting\Money\Provider` register or boot methods are called.

Removing the cache before installing the module seems to do the trick:
```
rm bootstrap/cache/config.php
composer require akaunting/laravel-money
php artisan vendor:publish --tag=money
php artisan config:cache
```

This is a Laravel quirk - nothing to do with this module. Make a general note of clearing the config cache before installing any new module.

**Comment by mlambley** [comment]
Also FYI this is the script which I used to see the error on Laravel v8.27.0, just in case you have any ideas on how to refactor the code to work around this particular quirk.

```
# Completely remove module, and reload cache
composer remove akaunting/laravel-money
rm config/money.php
rm bootstrap/cache/config.php
php artisan cache:clear
php artisan config:cache
# Now install and see the error
composer require akaunting/laravel-money
```

```
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   TypeError

  Argument 1 passed to Akaunting\Money\Currency::setCurrencies() must be of the type array, null given, called in 
/home/vagrant/my-site/vendor/akaunting/laravel-money/src/Provider.php on line 22
```
