### ISSUE TITLE
Convert question

### ISSUE THREAD

**Issue by fridzema** [akaunting/money#6]
Hello, 

Maybe it is a stupid question but i want to know why.. 
In am wondering why you have to convert manually to get proper the proper price of something.
For example i want to store an item with a price of €500 formatted, in my input i just fill 500 then its stored in a decimal field exact like 500.00

I am expecting that i would standard format to €500 but without the convert option it gets €5.

Can someone explain this maybe why this is happening?

**Comment by fridzema** [comment]
Sorry i already know!

**Comment by Thijmen** [comment]
@fridzema Could you tell us what you did to make it work? Currently facing it myself.

**Comment by fridzema** [comment]
@Thijmen don't know for sure anymore, but i think there was something wrong with my calculations what was causing this issue.

**Comment by Thijmen** [comment]
Ah, I put a string in my Money::EUR method in stead of a float... silly me.
