### ISSUE TITLE
Euro symbol gets rendered as text

### ISSUE THREAD

**Issue by koenhendriks** [akaunting/money#7]
Hello,

I'm using the the`money()` helper to show my totals in ChartJS. ChartJS renders in a canvas and my setup is the following for the labels:

```
new Chart({
...
    label: '2018: {{ money(12345678,'EUR',true) }}',
...
    label: '2017: {{ money(12345678,'USD',true) }}',
...
}
```

The USD symbol ($) works fine with ChartJS but the EUR symbol (€) gets rendered as `&euro;`

See this image for clarification:
![screenshot from 2018-02-22 10-53-14](https://user-images.githubusercontent.com/4124579/36531559-9aea0d58-17be-11e8-9320-73e44a7005a5.png)

PS: Might be a ChartJS issue, not sure.

**Comment by denisdulici** [comment]
Hello,

What is the version of your ChartJS?

Regards

**Comment by koenhendriks** [comment]
I'm using the latest from their repo releases, Version: 2.7.1

**Comment by denisdulici** [comment]
I'm not really able to reproduce such an issue :cry:

**Comment by TarasKovalyk** [comment]
@koenhendriks did you resolve this issue?

**Comment by koenhendriks** [comment]
I have no idea haha I don't think so.
